[package]
name = "agent"
version = "0.1.0"
authors = ["Andrey Daraschenka <andrei.daraschenka@leverx.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
async-std = "1.0.1"
async-trait = "0.1.48"
cfg-if = "1.0.0"
serde = "1.0"
serde_json = "1.0"
sentry = "0.22.0"
sysinfo = "0.16.5"
